In [1]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_ind
import time

In [2]:
zs = pd.read_table('/oak/stanford/groups/jpriest/cnv_ukb/cnv_constraint_zscores_20190430.tsv',
                   names=['Gene','z','pLI'], 
                   index_col='Gene')
zs.head()

              z       pLI
Gene
BRCA2  3.402038  0.991096
BRCA1  2.570469  0.984025
APC    2.085995  0.945645
ATM    1.242243  0.989235
MSH2   1.240663  0.988295

In [3]:
sets = pd.read_table('/oak/stanford/groups/jpriest/cnv_ukb/resources/HPO_pheno_to_gene.txt', skiprows=0,
                     names=['hpoID','hpolabel','geneID','Gene'])
sets.head()

        hpoID                                  hpolabel  geneID   Gene
0  HP:0001459                        1-3 toe syndactyly    2737   GLI3
1  HP:0006088  1-5 finger complete cutaneous syndactyly   64327  LMBR1
2  HP:0010708                     1-5 finger syndactyly    6469    SHH
3  HP:0010708                     1-5 finger syndactyly   64327  LMBR1
4  HP:0010713                        1-5 toe syndactyly    2737   GLI3

In [4]:
sets['hpoID'].value_counts().shape

(8524,)

In [5]:
load = True
if load:
    hpo_t = pd.read_table("/oak/stanford/groups/jpriest/cnv_ukb/cnv_constraint_hpo_enrichment_20190430.tsv")
else:
    hpo_t = pd.DataFrame()
    t = time.time()
    for hpo in sets['hpoID'].value_counts().index:
        # select rows
        in_set = sets.query('hpoID == @hpo and Gene in @zs.index')
        out_of_set = sets.query('hpoID != @hpo and Gene in @zs.index')
        if in_set.shape[0] == 0 or out_of_set.shape[0] == 0:
            continue
        # select genes
        in_set_z = zs.loc[in_set['Gene'],'z']
        out_of_set_z = zs.loc[out_of_set['Gene'],'z']
        # compute mean shift, t-test p-value
        deltaZ = in_set_z.mean() - out_of_set_z.mean()
        _,p = ttest_ind(in_set_z.values, out_of_set_z.values, equal_var=False, nan_policy='omit')
        # append
        hpo_t = hpo_t.append([[hpo, in_set.iloc[0,:]['hpolabel'], deltaZ, p, in_set_z.shape[0]]])
        if hpo_t.shape[0] % 200 == 0:
            print(hpo_t.shape[0], time.time()-t)
            t=time.time()
    hpo_t.columns = ['hpoID','hpoLabel','deltaZ','pValue','nGenes']
hpo_t.head()

,hpoID,hpoLabel,deltaZ,pValue,nGenes
0,HP:0000707,Abnormality of the nervous system,-0.007672,0.009988,2619
1,HP:0012638,Abnormality of nervous system physiology,-0.007689,0.014391,2433
2,HP:0000152,Abnormality of head or neck,-0.004238,0.233858,2115
3,HP:0000234,Abnormality of the head,-0.004255,0.235575,2094
4,HP:0000924,Abnormality of the skeletal system,-0.006123,0.088247,2047

In [6]:
hpo_t['pValue'] = hpo_t['pValue'].astype(float)

In [7]:
hpo_t.query('nGenes >= 5 and deltaZ > 0').sort_values('pValue').head(20)

,hpoID,hpoLabel,deltaZ,pValue,nGenes
1178,HP:0002034,Abnormality of the rectum,0.091344,0.005468,74
910,HP:0100006,Neoplasm of the central nervous system,0.084712,0.005929,107
452,HP:0011792,Neoplasm by histology,0.065458,0.006319,228
549,HP:0002027,Abdominal pain,0.084144,0.006739,177
1321,HP:0100834,Neoplasm of the large intestine,0.206365,0.006946,67
1612,HP:0100273,Neoplasm of the colon,0.277430,0.007167,49
904,HP:0010787,Genital neoplasm,0.133163,0.008309,102
730,HP:0008069,Neoplasm of the skin,0.064637,0.008358,140
973,HP:0100242,Sarcoma,0.084586,0.008506,103
573,HP:0000953,Hyperpigmentation of the skin,0.079611,0.008726,178
708,HP:0007379,Neoplasm of the genitourinary tract,0.098904,0.009468,139
1093,HP:0100568,Neoplasm of the endocrine system,0.098258,0.009500,86
776,HP:0004375,Neoplasm of the nervous system,0.064810,0.009648,133
1509,HP:0030063,Neuroepithelial neoplasm,0.149086,0.010027,53
1459,HP:0030060,Nervous tissue neoplasm,0.145911,0.010284,54
1460,HP:0030061,Neuroectodermal neoplasm,0.145911,0.010284,54
691,HP:0002250,Abnormal large intestine morphology,0.092780,0.010350,146
1106,HP:0010785,Gonadal neoplasm,0.151483,0.011309,79
1374,HP:0100615,Ovarian neoplasm,0.207854,0.011374,57
1864,HP:0003003,Colon cancer,0.336048,0.012941,37

In [15]:
hpo_t.query('nGenes >= 5 and deltaZ < 0').sort_values('pValue').head(50)

,hpoID,hpoLabel,deltaZ,pValue,nGenes
225,HP:0000648,Optic atrophy,-0.028272,5.787128e-13,430
651,HP:0012072,Aciduria,-0.036503,3.258807e-12,155
614,HP:0001344,Absent speech,-0.034383,2.544988e-10,158
208,HP:0012795,Abnormality of the optic disc,-0.026035,3.251769e-10,467
1019,HP:0009136,Duplication involving bones of the feet,-0.044283,4.473983e-09,92
832,HP:0003355,Aminoaciduria,-0.035638,7.014999e-09,115
1048,HP:0001829,Foot polydactyly,-0.043610,1.315878e-08,88
545,HP:0010442,Polydactyly,-0.032821,4.196554e-08,182
330,HP:0005280,Depressed nasal bridge,-0.026340,4.609781e-08,303
1119,HP:0001162,Postaxial hand polydactyly,-0.035859,6.691444e-08,80
872,HP:0002098,Respiratory distress,-0.031543,9.298491e-08,106
758,HP:0002803,Congenital contracture,-0.039506,9.772703e-08,120
845,HP:0002804,Arthrogryposis multiplex congenita,-0.044961,1.298762e-07,102
323,HP:0012447,Abnormal myelination,-0.025186,1.378331e-07,318
709,HP:0001161,Hand polydactyly,-0.036818,1.798595e-07,135
879,HP:0100259,Postaxial polydactyly,-0.031563,1.936862e-07,106
784,HP:0011220,Prominent forehead,-0.028556,3.646785e-07,122
1614,HP:0009833,Abnormal middle phalanx morphology of the hand,-0.049197,4.841070e-07,44
521,HP:0010864,"Intellectual disability, severe",-0.033679,5.679883e-07,185
1208,HP:0000194,Open mouth,-0.056514,6.686574e-07,61
705,HP:0011400,Abnormal CNS myelination,-0.032713,7.054619e-07,147
419,HP:0000556,Retinal dystrophy,-0.024817,8.032898e-07,234
277,HP:0001311,Abnormal nervous system electrophysiology,-0.025537,8.216947e-07,362
1371,HP:0010579,Cone-shaped epiphysis,-0.043933,8.307135e-07,58
953,HP:0003498,Disproportionate short stature,-0.032277,1.160476e-06,95
435,HP:0001272,Cerebellar atrophy,-0.021313,1.193136e-06,235
1470,HP:0100257,Ectrodactyly,-0.050898,1.245956e-06,50
1634,HP:0009843,Aplasia/Hypoplasia of the middle phalanges of ...,-0.048390,1.656292e-06,42
446,HP:0002020,Gastroesophageal reflux,-0.030116,2.298428e-06,212
1493,HP:0001171,Split hand,-0.048350,2.405590e-06,49
1405,HP:0001992,Organic aciduria,-0.036550,3.236982e-06,56
1315,HP:0100258,Preaxial polydactyly,-0.048618,3.999616e-06,61
1129,HP:0011815,Cephalocele,-0.029945,4.194930e-06,79
1130,HP:0002084,Encephalocele,-0.029945,4.194930e-06,79
1756,HP:0003429,CNS hypomyelination,-0.033280,4.943743e-06,41
1150,HP:0200134,Epileptic encephalopathy,-0.031529,6.265016e-06,77
1372,HP:0006829,Severe muscular hypotonia,-0.039879,7.425345e-06,57
150,HP:0001251,Ataxia,-0.018976,8.561779e-06,630
392,HP:0000501,Glaucoma,-0.023773,8.572504e-06,252
603,HP:0000662,Nyctalopia,-0.027301,8.892543e-06,157
138,HP:0004305,Involuntary movements,-0.018202,9.053138e-06,641
1462,HP:0002323,Anencephaly,-0.045268,9.718452e-06,52
443,HP:0030044,Flexion contracture of digit,-0.024717,1.062020e-05,209
2275,HP:0005435,Impaired T cell function,-0.087010,1.076791e-05,24
618,HP:0011338,Abnormality of mouth shape,-0.037946,1.260140e-05,146
510,HP:0005930,Abnormality of epiphysis morphology,-0.029195,1.672015e-05,199
331,HP:0030178,Abnormality of central nervous system electrop...,-0.026166,1.690843e-05,289
2427,HP:0012762,Cerebral white matter atrophy,-0.035491,1.864271e-05,21
1224,HP:0001850,Abnormality of the tarsal bones,-0.030149,2.151057e-05,69
1701,HP:0011840,Abnormality of T cell physiology,-0.058611,2.182912e-05,38

In [9]:
if not load:
    hpo_t.to_csv('/oak/stanford/groups/jpriest/cnv_ukb/cnv_constraint_hpo_enrichment_20181217.tsv', sep='\t')

In [10]:
hpo_t.query('deltaZ > 0 and pValue < 0.01').sort_values('deltaZ', ascending=False).head(20)

,hpoID,hpoLabel,deltaZ,pValue,nGenes
6280,HP:0006778,Benign genitourinary tract neoplasm,1.165369,0.004459,2
6141,HP:0006719,Benign gastrointestinal tract tumors,1.165369,0.004459,2
6137,HP:0030410,Sebaceous gland carcinoma,1.165369,0.004459,2
5318,HP:0006758,Malignant genitourinary tract tumor,1.073453,0.007271,3
1612,HP:0100273,Neoplasm of the colon,0.277430,0.007167,49
1321,HP:0100834,Neoplasm of the large intestine,0.206365,0.006946,67
904,HP:0010787,Genital neoplasm,0.133163,0.008309,102
708,HP:0007379,Neoplasm of the genitourinary tract,0.098904,0.009468,139
1093,HP:0100568,Neoplasm of the endocrine system,0.098258,0.009500,86
1178,HP:0002034,Abnormality of the rectum,0.091344,0.005468,74
910,HP:0100006,Neoplasm of the central nervous system,0.084712,0.005929,107
973,HP:0100242,Sarcoma,0.084586,0.008506,103
549,HP:0002027,Abdominal pain,0.084144,0.006739,177
573,HP:0000953,Hyperpigmentation of the skin,0.079611,0.008726,178
5364,HP:0011939,3-4 finger cutaneous syndactyly,0.076933,0.000902,3
452,HP:0011792,Neoplasm by histology,0.065458,0.006319,228
776,HP:0004375,Neoplasm of the nervous system,0.064810,0.009648,133
730,HP:0008069,Neoplasm of the skin,0.064637,0.008358,140
5129,HP:0011784,Thyrotoxicosis with diffuse goiter,0.036587,0.009869,2

In [11]:
sets.query('hpoID == "HP:0040181"')

             hpoID     hpolabel  geneID   Gene
297326  HP:0040181  Chapped lip    3853  KRT6A

In [12]:
hpo_t.query('deltaZ < 0 and pValue < 0.01').sort_values('deltaZ').head(10)

,hpoID,hpoLabel,deltaZ,pValue,nGenes
4717,HP:0006549,Unilateral primary pulmonary dysgenesis,-0.175750,0.000000,4
4742,HP:0011590,Double aortic arch,-0.175750,0.000000,4
5626,HP:0006699,Premature atrial contractions,-0.175750,0.000000,3
6223,HP:0040266,Proximal upper limb muscle hypertrophy,-0.175749,0.000000,2
6210,HP:0040265,Upper limb muscle hypertrophy,-0.175749,0.000000,2
6529,HP:0040278,Prolactinoma,-0.175749,0.000000,2
6682,HP:0040025,Clinodactyly of the 4th finger,-0.175749,0.000000,2
6098,HP:0040217,Elevated hemoglobin A1c,-0.175749,0.000000,2
5512,HP:0012398,Peripheral edema,-0.169074,0.000428,3
3965,HP:0001664,Torsade de pointes,-0.158521,0.000093,7

In [13]:
hpo_t.query('deltaZ > 0 and pValue < 0.01 and nGenes < 100').sort_values('deltaZ', ascending=False).head(10)

,hpoID,hpoLabel,deltaZ,pValue,nGenes
6137,HP:0030410,Sebaceous gland carcinoma,1.165369,0.004459,2
6141,HP:0006719,Benign gastrointestinal tract tumors,1.165369,0.004459,2
6280,HP:0006778,Benign genitourinary tract neoplasm,1.165369,0.004459,2
5318,HP:0006758,Malignant genitourinary tract tumor,1.073453,0.007271,3
1612,HP:0100273,Neoplasm of the colon,0.277430,0.007167,49
1321,HP:0100834,Neoplasm of the large intestine,0.206365,0.006946,67
1093,HP:0100568,Neoplasm of the endocrine system,0.098258,0.009500,86
1178,HP:0002034,Abnormality of the rectum,0.091344,0.005468,74
5364,HP:0011939,3-4 finger cutaneous syndactyly,0.076933,0.000902,3
5129,HP:0011784,Thyrotoxicosis with diffuse goiter,0.036587,0.009869,2

In [14]:
sets.query("hpoID == 'HP:0001417' and Gene in @zs.index")

             hpoID              hpolabel  geneID    Gene
496815  HP:0001417  X-linked inheritance    9227    LRAT
496818  HP:0001417  X-linked inheritance      24   ABCA4
496821  HP:0001417  X-linked inheritance    5148   PDE6G
496833  HP:0001417  X-linked inheritance   10804    GJB6
496866  HP:0001417  X-linked inheritance    4724  NDUFS4
496867  HP:0001417  X-linked inheritance  440435  GPR179
496874  HP:0001417  X-linked inheritance    7299     TYR
496876  HP:0001417  X-linked inheritance   84100    ARL6
496885  HP:0001417  X-linked inheritance    2706    GJB2
496907  HP:0001417  X-linked inheritance    4286    MITF
496910  HP:0001417  X-linked inheritance   23746   AIPL1
496928  HP:0001417  X-linked inheritance    7401   CLRN1
496930  HP:0001417  X-linked inheritance    1259   CNGA1
496958  HP:0001417  X-linked inheritance    5949    RBP3
496982  HP:0001417  X-linked inheritance   23418    CRB1
496985  HP:0001417  X-linked inheritance    1406     CRX
496994  HP:0001417  X-linked inheritance    3481    IGF2
497012  HP:0001417  X-linked inheritance    6094    ROM1